feat(cmd/ndt7-client): support gathering profile info
m-lab/ndt7-client-go pull request #60
Opened 2021-05-22 07:11 UTC by bassosimone

Useful to investigate https://github.com/m-lab/ndt7-client-go/issues/59.

2021-06-03 14:42 UTC, robertodauria requested changes
Just a few little things, then <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - thanks!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-go/60#-:-MbHJFEL578xUAeB8eN7:bkslnxj)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @bassosimone)

___
*[cmd/ndt7-client/main.go, line 41 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-go/60#-MbHIsOGAqwr6PuoDkYv:-MbHIsOHCSC25dkUHYS1:b9l63sz) ([raw file](https://github.com/m-lab/ndt7-client-go/blob/6de87b916e7a6ed17a33c21c603cda84302fdfb3/cmd/ndt7-client/main.go#L41)):*
> ```Go
> // download.
> //
> // The `-cpuprofile` flag defines the file where to write a CPU profile
> ```

`s/cpuprofile/profile/`
___
*[cmd/ndt7-client/main.go, line 120 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-go/60#-MbHIxxi6vNBYcMlLS3k:-MbHIxxj636RU5dqD8xX:b2j9bvw) ([raw file](https://github.com/m-lab/ndt7-client-go/blob/6de87b916e7a6ed17a33c21c603cda84302fdfb3/cmd/ndt7-client/main.go#L120)):*
> ```Go
> var (
> 	flagProfile = flag.String("profile", "",
> 		"file where to store cpuprofile (see https://blog.golang.org/pprof)")
> ```

`s/cpuprofile/pprof profile/`
___
*[cmd/ndt7-client/main.go, line 284 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-go/60#-MbHJ0Xs3_s2WLQQha7b:-MbHJ0Xs3_s2WLQQha7c:bo5a1gd) ([raw file](https://github.com/m-lab/ndt7-client-go/blob/6de87b916e7a6ed17a33c21c603cda84302fdfb3/cmd/ndt7-client/main.go#L284)):*
> ```Go
> 	flag.Parse()
> 
> 	if *flagProfile != "" {
> ```

Could we add a warning that enabling the profiler may impact performance?


<!-- Sent from Reviewable.io -->

2021-06-07 11:48 UTC, bassosimone reviewed
applied the required changes

2021-06-07 11:48 UTC, bassosimone commented on cmd/ndt7-client/main.go
> +// The `-cpuprofile` flag defines the file where to write a CPU profile
```suggestion
// The `-profile` flag defines the file where to write a CPU profile
```

2021-06-07 11:48 UTC, bassosimone commented on cmd/ndt7-client/main.go
> +		"file where to store cpuprofile (see https://blog.golang.org/pprof)")
```suggestion
		"file where to store pprof profile (see https://blog.golang.org/pprof)")
```

2021-06-07 11:48 UTC, bassosimone commented on cmd/ndt7-client/main.go
> +	if *flagProfile != "" {
```suggestion
	if *flagProfile != "" {
		log.Printf("warning: using -profile will obviously reduce the performance")	
```

2021-06-07 11:50 UTC, bassosimone commented on cmd/ndt7-client/main.go
> +		log.Printf("warning: using -profile will obviously reduce the performance")
```suggestion
		log.Printf("warning: using -profile will reduce the performance")	
```

2021-06-07 11:51 UTC, robertodauria approved these changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-go/60)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @bassosimone)



<!-- Sent from Reviewable.io -->

2021-06-07 11:52 UTC, merged